### ISSUE TITLE
Code gives out the error "ImportError: No module named python2x"

### ISSUE THREAD

**Issue by abhijeetg12** [donghyunlee/dtp#1]
RMS prop function is using OrderedDict, but the import for that gives out the following error. 

Traceback (most recent call last):
  File "conti_dtp.py", line 4, in <module>
    from util import *
  File "/home/abhijeet/Desktop/Theory of DL/Project/dtp/util.py", line 5, in <module>
    from theano.compat.python2x import OrderedDict
ImportError: No module named python2x

**Comment by XDUSPONGE** [comment]
> RMS prop function is using OrderedDict, but the import for that gives out the following error.
> 
> Traceback (most recent call last):
> File "conti_dtp.py", line 4, in 
> from util import *
> File "/home/abhijeet/Desktop/Theory of DL/Project/dtp/util.py", line 5, in 
> from theano.compat.python2x import OrderedDict
> ImportError: No module named python2x
Hello, I think you can change the code 
into from collections import OrderedDict
and I have test it
